config/routes.rb
Rails.application.routes.draw do

  root :to => 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'books' => 'homes#index', as: 'main_page'
  get 'books' => 'homes#new'
  post 'books' => 'homes#create'
  get 'books/:id' => 'homes#show', as: 'show_room'
  get 'books/:id/edit' => 'homes#edit', as: 'edit_room'
  patch 'books/:id' => 'homes#update', as: 'update_book'
  delete 'books/:id' => 'homes#destroy', as: 'destroy_book' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def show
    @book = Blog.find(params[:id])
  end

  def index
    @book = Blog.all
  end

  def new
    @book = Blog.new
  end

  def create
    book = Blog.new(book_params)
    book.save
    redirect_to show_room_path(book.id)
  end

  def edit
    @book = Blog.find(params[:id])
  end

  def update
    book = Blog.find(params[:id])
    book.update(book_params)
    redirect_to books_path
  end

  def destroy
    book = Blog.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:blog).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/edit.html.erb
<h1>Editing Book</h1>


<h1>編集画面</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '保存' %>
  <%= link_to "show", show_room_path(@book.id) %>
  <%= link_to "back", main_page_path %>
<%= link_to "destroy", destroy_book_path, method: :delete %>


<% end %>

app/views/homes/index.html.erb
<h1>メインページ</h1>
<p>Title</p><p>Body</p>
<% @book.each do |book| %>
<span><%= book.title %></span>
<span><%= book.body %></span>
<%= link_to "show", show_room_path(book.id) %>
<%= link_to "edit", edit_room_path(book.id) %>
<%= link_to "destroy", destroy_book_path(book.id), method: :delete %>

<% end %>



<h1>New book </h1>
<%= form_with model:@book, url:'/books',local:true do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Body</h4>
<%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/homes/show.html.erb
<h4>Title</h4><%= @book.title %>

<%= link_to "edit", edit_room_path(@book.id) %>
<%= link_to "back", main_page_path %>

app/views/homes/top.html.erb
<h1>ようこそ</h1>
<p>ここは本の感想をレビューするサイトです</p>
<span>
<%= link_to "start",books_path %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>